---
title: "Assingment 3"
author: "Muhammad Usman (437790)"
date: "4/24/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Exercise 1

Consider a [FizzBuzz problem](https://codegolf.stackexchange.com/questions/58615/1-2-fizz-4-buzz). The program should write numbers from 1 to 100, separated by a newline, but multiples of 3 and of 5 should be replaced with "Fizz" and "Buzz" respectively. For numbers which are multiples of both 3 and 5 print "FizzBuzz". Here are some solutions, which are not readable:

z <- c(1:100)
for(i in z){
  if (i %% 3 == 0)  
    print("Fizz")      
  else if(i %% 5 == 0)
    print("Buzz")      
  else if(i %% 3 == 0 && i %% 5 ==0)
    print("FizzBuzz")      
  else 
    print(i)                        
  
}

#Exercise 2.1

## a function to compute  Fibonachi numbers

fibonacci <- function(n) {
if(n <= 1) {
return(n)
} else {
return(fibonacci(n-1) + fibonacci(n-2))
}


##2.2 Write a function which reverses digits in an integer number (for example 7245 -> 5427). The function should be documented, with type hints, and appropriate comments.
 
rvrs_num <- function(x){ 
  n <- trunc(log10(x)) # now many powers of 10 are we dealing with 
  x_rem <- x # remaining integers to be reversed 
  x_out <- 0 # for storing output 
  for(i in n:0){
    x_out <- x_out + (x_rem %/% 10^i)*10^(n-i) # multiplication & addition  
    x_rem <- x_rem - (x_rem %/% 10^i)*10^i # multiplication & subtraction 
  } 
  return(x_out) 
}

rvrs_num(7868)
