---
title: "Muhammad Uaman"
author: "Muhammad Usman"
date: "5/27/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
setwd("E:\\")
library(meta)
library(metafor)
library(dplyr)
library("readxl")

```



```{r}
data<- read_excel("metaanalysis_data.xlsx") #reading data
```



```{r}

m <- metagen(TE=Mean_boys_play_male,
             seTE=SD_boys_play_male,
             data=data,
             studlab=paste(Study),
             comb.fixed = TRUE,
             comb.random = FALSE)
m                                                                                     

```



```{r} 
#with random effects
m_re <- metagen(TE=Mean_boys_play_male,
                seTE=SD_boys_play_male,
                data=data,
                studlab=paste(Study),
                comb.fixed = FALSE,
                comb.random = TRUE)
m_re

```


```{r}
m %>% forest(sortvar=TE)

m_re %>% forest(sortvar=TE)
```


```{r}
m %>% funnel(contour = c(.95,.975,.99),                                                                                     col.contour=c("darkblue","blue","lightblue"))+  
legend(1.4, 0, c("p < 0.05", "p<0.025", "< 0.01"),bty = "n",
fill=c("darkblue","blue","lightblue"))
```

